version: '3'

services:
 cezerin2:
   image: docker.pkg.github.com/albis-group/leasekitsdk/albis-cezerin2
   ports:
     - 3001:80
   environment:
     - DB_HOST=db
     - DB_PORT=27017
     - DB_NAME=shop
     - DB_USER=
     - DB_PASS=
     - API_BASE_URL=http://localhost:3001/api/v1
     - STORE_BASE_URL=http://localhost:3000
     - ADMIN_BASE_URL=http://localhost:3002
     - ASSETS_BASE_URL=http://localhost:3001
   volumes:
     - ./content-on-host:/var/www/cezerin2/public/content
   depends_on:
     - db
   restart: always

 cezerin2-store:
   image: docker.pkg.github.com/albis-group/leasekitsdk/albis-cezerin2-store
   environment:
     - API_BASE_URL=http://cezerin2/api/v1
     - AJAX_BASE_URL=http://cezerin2/ajax
     - ASSETS_BASE_URL=http://localhost:3001
     - ALBIS_SHOP_USERNAME=TO_CHANGE_USERNAME # TO CHANGE BY USER
     - ALBIS_SHOP_PASSWORD=TO_CHANGE_PASSWORD # TO CHANGE BY USER
     - AUTH0_USERNAME=TO_CHANGE_USERNAME # TO CHANGE BY USER
     - AUTH0_PASSWORD=TO_CHANGE_PASSWORD # TO CHANGE BY USER
     - ALBIS_SHOP_REALM=TO_CHANGE_REALM # TO CHANGE BY USER
     - SDK_ENDPOINT=TO_CHANGE_SDK_ENDPOINT # TO CHANGE BY USER
     - API_STAGE=TO_CHANGE_SDK_API_STAGE # TO CHANGE BY USER
     - NODE_ENV=TO_CHANGE_SDK_NODE_ENV # TO CHANGE BY USER
     - RECEIVER_ENDPOINT=TO_CHANGE_RECEIVER_ENDPOINT # TO CHANGE BY USER
     - RECEIVER_FAIL_EMAILS=TO_CHANGE_RECEIVER_FAIL_EMAILS # TO CHANGE BY USER
   ports:
     - 3000:80
   depends_on:
     - cezerin2
   restart: always

 admin:
   image: docker.pkg.github.com/albis-group/leasekitsdk/albis-cezerin2-admin
   ports:
     - 3002:80
   environment:
   - API_BASE_URL=http://localhost:3001/api/v1
   - API_WEB_SOCKET_URL=ws://localhost:3001
   depends_on:
     - cezerin2
   restart: always

 db:
   image: mongo:3.6
   ports:
     - 27017:27017
   volumes:
     - ./db-on-host:/data/db
   restart: always